
ROWS=10000
COLS=10000
COMPFLAGS=-O3 -qhot -mcpu=power9 -mtune=power9 -maltivec

matmul_gpuoffload	:	main.c mm.c
	xlc -o matmul_gpuoffload main.c mm.c -qsmp=omp -qoffload ${COMPFLAGS} -qtgtarch=sm_70 -lcudart -L/usr/local/cuda/lib64 -DROWSIZE=$(ROWS) -DCOLSIZE=$(COLS) -D__OPENMP_GPU__

clean	:
	rm matmul_gpuoffload 
